# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
#retriveing weather data and placing into dataframe
summ_city_info = "Output/summarycityinfo.csv"
summ_city_info_df = pd.read_csv(summ_city_info)
summ_city_info_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,date
0,Poum,-20.2333,164.0167,299.68,71,26,4.87,NC,1615590416
1,George Town,5.4112,100.3354,297.63,94,20,1.54,MY,1615590416
2,Port Elizabeth,-33.9180,25.5701,293.15,94,0,2.40,ZA,1615590355
3,Ketchikan,55.3422,-131.6461,276.15,60,90,3.09,US,1615590361
4,Sungai Raya,0.7000,108.9000,297.46,89,61,2.27,ID,1615590418
...,...,...,...,...,...,...,...,...,...
588,Urengoy,65.9667,78.3667,256.94,91,100,9.36,RU,1615590887
589,Ostrovnoy,68.0531,39.5131,262.50,90,96,7.42,RU,1615590888
590,Lichtenfels,50.1457,11.0593,277.08,77,100,1.34,DE,1615590888
591,Russell,32.3502,-85.1999,297.53,41,1,3.09,US,1615590889
592,Bloomsburg,41.0037,-76.4549,287.13,19,1,2.57,US,1615590797

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
#configuring gmaps
gmaps.configure(api_key=g_key)

In [4]:
#pulling and setting info for heat map
locations_sum = summ_city_info_df[["Lat","Lng"]]
humidity = summ_city_info_df["Humidity"].astype(float)
locations_sum

         Lat       Lng
0   -20.2333  164.0167
1     5.4112  100.3354
2   -33.9180   25.5701
3    55.3422 -131.6461
4     0.7000  108.9000
..       ...       ...
588  65.9667   78.3667
589  68.0531   39.5131
590  50.1457   11.0593
591  32.3502  -85.1999
592  41.0037  -76.4549

[593 rows x 2 columns]

In [5]:
#creating heat maps on location and humidity

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations_sum, weights=humidity, dissipating=False, max_intensity=200, point_radius=5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
markers = gmaps.marker_layer(locations_sum)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [7]:
summ_city_info_df.describe()

,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,date
count,593.000000,593.000000,593.000000,593.000000,593.000000,593.000000,5.930000e+02
mean,19.622542,15.241049,285.008954,71.853288,48.632378,3.929174,1.615591e+09
std,33.921495,91.428023,15.446806,21.841808,39.192048,2.714998,1.696983e+02
min,-54.800000,-175.200000,241.940000,5.000000,0.000000,0.130000,1.615590e+09
25%,-7.300000,-65.102300,276.040000,61.000000,5.000000,1.780000,1.615591e+09
50%,21.346900,19.961900,290.790000,77.000000,41.000000,3.460000,1.615591e+09
75%,50.100100,92.750000,297.400000,89.000000,90.000000,5.430000,1.615591e+09
max,78.218600,178.416700,304.440000,100.000000,100.000000,18.520000,1.615591e+09

In [8]:
#shortening dataframe by weather conditions and dropping
hotel_df = summ_city_info_df.loc[(summ_city_info_df["Max Temp"] < 300) &
                                    (summ_city_info_df["Max Temp"] > 250) &
                                    (summ_city_info_df["Wind Speed"] < 5) &
                                    (summ_city_info_df["Cloudiness"] == 0),:]
hotel_df = hotel_df.dropna(how='any')
hotel_df = hotel_df.reset_index(drop=True)
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,date
0,Port Elizabeth,-33.9180,25.5701,293.15,94,0,2.40,ZA,1615590355
1,Cape Town,-33.9258,18.4232,290.69,94,0,2.06,ZA,1615589582
2,Mar del Plata,-38.0023,-57.5575,291.26,63,0,3.09,AR,1615590446
3,Saint-Philippe,-21.3585,55.7679,295.11,69,0,3.60,RE,1615590453
4,Ampanihy,-24.7000,44.7500,295.00,77,0,4.55,MG,1615590456
5,Bubaque,11.2833,-15.8333,299.19,63,0,4.86,GW,1615590478
6,Bandarbeyla,9.4942,50.8122,297.65,74,0,3.45,SO,1615590479
7,Ancud,-41.8697,-73.8203,287.29,77,0,3.09,CL,1615590325
8,Tuatapere,-46.1333,167.6833,290.37,72,0,0.89,NZ,1615590488
9,Turgutlu,38.4953,27.6997,277.09,87,0,1.03,TR,1615590501
10,Comodoro Rivadavia,-45.8667,-67.5000,293.15,49,0,3.09,AR,1615590329
11,Khilok,51.3674,110.4676,267.67,88,0,1.87,RU,1615590508
12,Saint-Pierre,-21.3393,55.4781,296.87,69,0,3.60,RE,1615590512
13,Pisco,-13.7000,-76.2167,297.44,78,0,3.60,PE,1615590526
14,Kayes,14.0000,-11.0000,298.26,12,0,4.50,ML,1615590548
15,Forbes,-33.3833,148.0167,299.26,71,0,3.58,AU,1615590562
16,Saint-FranÃ§ois,46.4154,3.9054,279.94,76,0,2.57,FR,1615590566
17,Tura,25.5198,90.2201,293.17,56,0,1.20,IN,1615590575
18,Tezu,27.9167,96.1667,293.09,53,0,1.60,IN,1615590577
19,Kuchinarai,16.5410,104.0500,295.15,78,0,2.06,TH,1615590578
20,Khanbari,27.3747,87.2039,288.87,40,0,1.63,NP,1615590579
21,Araouane,18.9048,-3.5265,292.61,24,0,4.90,ML,1615590579
22,Dali,25.7000,100.1833,281.56,65,0,0.81,CN,1615590589
23,Eyl,7.9803,49.8164,296.58,82,0,4.58,SO,1615590604
24,Bira,49.0000,132.4667,268.59,82,0,1.44,RU,1615590629
25,Tarnos,43.5417,-1.4628,280.73,81,0,2.06,FR,1615590643
26,Dolinsk,47.3500,142.8000,270.15,80,0,1.00,RU,1615590644
27,Trelew,-43.2490,-65.3051,296.42,28,0,4.85,AR,1615590562
28,Caravelas,-17.7125,-39.2481,296.46,80,0,2.65,BR,1615590648
29,Baicheng,45.6167,122.8167,272.82,52,0,3.06,CN,1615590654
30,Ajdabiya,30.7554,20.2263,286.07,55,0,3.41,LY,1615590655
31,Santiago,-33.4569,-70.6483,299.04,36,0,4.12,CL,1615589912
32,Salalah,17.0151,54.0924,295.15,78,0,1.03,OM,1615590665
33,Lazarev,52.2250,141.5131,268.38,78,0,2.98,RU,1615590706
34,Vostok,46.4856,135.8833,268.02,81,0,1.37,RU,1615590738
35,Saint-Leu,-21.1500,55.2833,296.42,69,0,3.60,RE,1615590747
36,Qandala,11.4720,49.8728,298.02,60,0,0.60,SO,1615590750
37,Cayenne,4.9333,-52.3333,296.02,94,0,4.57,GF,1615590751
38,Wangkui,46.8333,126.5000,267.87,76,0,2.55,CN,1615590678
39,Podor,16.6527,-14.9587,299.15,27,0,1.03,MR,1615590767
40,CamanÃ¡,-16.6228,-72.7111,296.72,82,0,3.18,PE,1615590812
41,Eureka,40.8021,-124.1637,286.96,69,0,1.34,US,1615590815
42,Gonder,12.6000,37.4667,290.86,30,0,2.37,ET,1615590830
43,Shabo,46.1326,30.3860,275.53,87,0,3.00,UA,1615590837
44,Ziway,7.9333,38.7167,292.82,50,0,2.69,ET,1615590853
45,Jiexiu,37.0244,111.9125,281.21,85,0,0.15,CN,1615590857
46,Bariloche,-41.1456,-71.3082,293.15,34,0,4.63,AR,1615590626
47,Bandrele,-12.9067,45.1914,298.15,94,0,1.03,YT,1615590863
48,Barcelos,41.5388,-8.6151,282.13,93,0,0.51,PT,1615590877
49,Talcahuano,-36.7167,-73.1167,294.15,60,0,3.60,CL,1615590880

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [9]:
#creating empty column to place hotel names in
hotel_df['Hotel Name'] = ""
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,date,Hotel Name
0,Port Elizabeth,-33.9180,25.5701,293.15,94,0,2.40,ZA,1615590355,
1,Cape Town,-33.9258,18.4232,290.69,94,0,2.06,ZA,1615589582,
2,Mar del Plata,-38.0023,-57.5575,291.26,63,0,3.09,AR,1615590446,
3,Saint-Philippe,-21.3585,55.7679,295.11,69,0,3.60,RE,1615590453,
4,Ampanihy,-24.7000,44.7500,295.00,77,0,4.55,MG,1615590456,
5,Bubaque,11.2833,-15.8333,299.19,63,0,4.86,GW,1615590478,
6,Bandarbeyla,9.4942,50.8122,297.65,74,0,3.45,SO,1615590479,
7,Ancud,-41.8697,-73.8203,287.29,77,0,3.09,CL,1615590325,
8,Tuatapere,-46.1333,167.6833,290.37,72,0,0.89,NZ,1615590488,
9,Turgutlu,38.4953,27.6997,277.09,87,0,1.03,TR,1615590501,
10,Comodoro Rivadavia,-45.8667,-67.5000,293.15,49,0,3.09,AR,1615590329,
11,Khilok,51.3674,110.4676,267.67,88,0,1.87,RU,1615590508,
12,Saint-Pierre,-21.3393,55.4781,296.87,69,0,3.60,RE,1615590512,
13,Pisco,-13.7000,-76.2167,297.44,78,0,3.60,PE,1615590526,
14,Kayes,14.0000,-11.0000,298.26,12,0,4.50,ML,1615590548,
15,Forbes,-33.3833,148.0167,299.26,71,0,3.58,AU,1615590562,
16,Saint-FranÃ§ois,46.4154,3.9054,279.94,76,0,2.57,FR,1615590566,
17,Tura,25.5198,90.2201,293.17,56,0,1.20,IN,1615590575,
18,Tezu,27.9167,96.1667,293.09,53,0,1.60,IN,1615590577,
19,Kuchinarai,16.5410,104.0500,295.15,78,0,2.06,TH,1615590578,
20,Khanbari,27.3747,87.2039,288.87,40,0,1.63,NP,1615590579,
21,Araouane,18.9048,-3.5265,292.61,24,0,4.90,ML,1615590579,
22,Dali,25.7000,100.1833,281.56,65,0,0.81,CN,1615590589,
23,Eyl,7.9803,49.8164,296.58,82,0,4.58,SO,1615590604,
24,Bira,49.0000,132.4667,268.59,82,0,1.44,RU,1615590629,
25,Tarnos,43.5417,-1.4628,280.73,81,0,2.06,FR,1615590643,
26,Dolinsk,47.3500,142.8000,270.15,80,0,1.00,RU,1615590644,
27,Trelew,-43.2490,-65.3051,296.42,28,0,4.85,AR,1615590562,
28,Caravelas,-17.7125,-39.2481,296.46,80,0,2.65,BR,1615590648,
29,Baicheng,45.6167,122.8167,272.82,52,0,3.06,CN,1615590654,
30,Ajdabiya,30.7554,20.2263,286.07,55,0,3.41,LY,1615590655,
31,Santiago,-33.4569,-70.6483,299.04,36,0,4.12,CL,1615589912,
32,Salalah,17.0151,54.0924,295.15,78,0,1.03,OM,1615590665,
33,Lazarev,52.2250,141.5131,268.38,78,0,2.98,RU,1615590706,
34,Vostok,46.4856,135.8833,268.02,81,0,1.37,RU,1615590738,
35,Saint-Leu,-21.1500,55.2833,296.42,69,0,3.60,RE,1615590747,
36,Qandala,11.4720,49.8728,298.02,60,0,0.60,SO,1615590750,
37,Cayenne,4.9333,-52.3333,296.02,94,0,4.57,GF,1615590751,
38,Wangkui,46.8333,126.5000,267.87,76,0,2.55,CN,1615590678,
39,Podor,16.6527,-14.9587,299.15,27,0,1.03,MR,1615590767,
40,CamanÃ¡,-16.6228,-72.7111,296.72,82,0,3.18,PE,1615590812,
41,Eureka,40.8021,-124.1637,286.96,69,0,1.34,US,1615590815,
42,Gonder,12.6000,37.4667,290.86,30,0,2.37,ET,1615590830,
43,Shabo,46.1326,30.3860,275.53,87,0,3.00,UA,1615590837,
44,Ziway,7.9333,38.7167,292.82,50,0,2.69,ET,1615590853,
45,Jiexiu,37.0244,111.9125,281.21,85,0,0.15,CN,1615590857,
46,Bariloche,-41.1456,-71.3082,293.15,34,0,4.63,AR,1615590626,
47,Bandrele,-12.9067,45.1914,298.15,94,0,1.03,YT,1615590863,
48,Barcelos,41.5388,-8.6151,282.13,93,0,0.51,PT,1615590877,
49,Talcahuano,-36.7167,-73.1167,294.15,60,0,3.60,CL,1615590880,

In [12]:
#for loop to find hotel name
for index, row in hotel_df.iterrows():
    try:
        latitude = row['Lat']
        longitude = row['Lng']
        request_url = f"https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={latitude},{longitude}&radius=5000&types=Lodging&key={g_key}"
        #print(base_url)
        response = requests.get(request_url).json()
        hotel_df.loc[index,'Hotel Name'] = response['results'][1]['name']
        #break
    except:
        hotel_df.loc[index,'Hotel Name'] = "No Hotel found within 5000 meters"

In [13]:
hotel_df.head(20)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,date,Hotel Name
0,Port Elizabeth,-33.9180,25.5701,293.15,94,0,2.40,ZA,1615590355,Gelvandale Stadium
1,Cape Town,-33.9258,18.4232,290.69,94,0,2.06,ZA,1615589582,Southern Sun Waterfront Cape Town
2,Mar del Plata,-38.0023,-57.5575,291.26,63,0,3.09,AR,1615590446,Gran Hotel Mar del Plata
3,Saint-Philippe,-21.3585,55.7679,295.11,69,0,3.60,RE,1615590453,"Chambres d'hÃ´te ""La TrinitÃ©"""
4,Ampanihy,-24.7000,44.7500,295.00,77,0,4.55,MG,1615590456,Ampanihy - Ouest Hospital
5,Bubaque,11.2833,-15.8333,299.19,63,0,4.86,GW,1615590478,"Casa Dora, Bubaque"
6,Bandarbeyla,9.4942,50.8122,297.65,74,0,3.45,SO,1615590479,Xooshle Group of Company
7,Ancud,-41.8697,-73.8203,287.29,77,0,3.09,CL,1615590325,Hotel Arena Gruesa
8,Tuatapere,-46.1333,167.6833,290.37,72,0,0.89,NZ,1615590488,Tuatapere Cemetery
9,Turgutlu,38.4953,27.6997,277.09,87,0,1.03,TR,1615590501,Palmcity Hotel Turgutlu
10,Comodoro Rivadavia,-45.8667,-67.5000,293.15,49,0,3.09,AR,1615590329,Hotel del Mar
11,Khilok,51.3674,110.4676,267.67,88,0,1.87,RU,1615590508,Rossel'khozbank
12,Saint-Pierre,-21.3393,55.4781,296.87,69,0,3.60,RE,1615590512,AlizÃ© Plage
13,Pisco,-13.7000,-76.2167,297.44,78,0,3.60,PE,1615590526,Hotel San Isidro Oficial
14,Kayes,14.0000,-11.0000,298.26,12,0,4.50,ML,1615590548,No Hotel found within 5000 meters
15,Forbes,-33.3833,148.0167,299.26,71,0,3.58,AU,1615590562,Lake Forbes Motel
16,Saint-FranÃ§ois,46.4154,3.9054,279.94,76,0,2.57,FR,1615590566,Mairie
17,Tura,25.5198,90.2201,293.17,56,0,1.20,IN,1615590575,"Click N Browse Internet Cafe, Sukbhir Bhawan, ..."
18,Tezu,27.9167,96.1667,293.09,53,0,1.60,IN,1615590577,Consumer Court
19,Kuchinarai,16.5410,104.0500,295.15,78,0,2.06,TH,1615590578,Kuchinarai Telephone Exchange

In [14]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [15]:
# Add marker layer ontop of heat map
hum_ = hotel_df["Humidity"].astype(float)

fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=hum_, dissipating=False, max_intensity=200, point_radius=5)
fig.add_layer(heat_layer)

markers = gmaps.marker_layer(locations)
fig.add_layer(markers)
fig

# Display figure

Figure(layout=FigureLayout(height='420px'))